# Generated by Django 6.0.5 on 2026-06-05 06:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='internal_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Calculated Internal Marks'),
        ),
        migrations.CreateModel(
            name='DailyAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('FULL', 'Full Present (Both Sessions)'), ('HALF', 'Half Day (One Session)'), ('ABSENT', 'Absent (No Sessions)')], default='FULL', max_length=10)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='erp.studentprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
