# Generated by Django 6.0.5 on 2026-06-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_studentprofile_internal_marks_dailyattendancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='1-1', help_text='e.g., 1-1, 1-2', max_length=10)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=150)),
                ('grade', models.CharField(help_text='e.g., S, A, B, C, F', max_length=5)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='erp.studentprofile')),
            ],
            options={
                'ordering': ['subject_code'],
                'unique_together': {('student', 'semester', 'subject_code')},
            },
        ),
    ]
