# Generated by Django 6.0.5 on 2026-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_studentsubjectgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_type',
            field=models.CharField(choices=[('REGULAR', 'Regular (4-Year Entry)'), ('LATERAL', 'Lateral Entry (Diploma to B.Tech 3-Year Entry)')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_performance_cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
